### ISSUE TITLE
error in pointnet2_ops_lib

### ISSUE THREAD

**Issue by zhangdongwei1998** [crane-papercode/3DMedT#3]
I would appreciate it if you could help,thanks.

when i run "pip install pointnet2_ops_lib/." there a error :

Building wheel for pointnet2-ops (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\python3.7\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dongw\\AppData\\Local\\Temp\\p
ip-req-build-ry1p4epw\\setup.py'"'"'; __file__='"'"'C:\\Users\\dongw\\AppData\\Local\\Temp\\pip-req-build-ry1p4epw\\setup.py'"'"';f = getattr(token
ize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().
replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\dongw\AppData\Local\Temp\pi
p-wheel-sl6h_j_v'
       cwd: C:\Users\dongw\AppData\Local\Temp\pip-req-build-ry1p4epw\
  Complete output (46 lines):
  No CUDA runtime is found, using CUDA_HOME='D:\Anaconda3\pkgs\cudatoolkit-10.2.89-hb195166_8'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pointnet2_ops
  copying pointnet2_ops\pointnet2_modules.py -> build\lib.win-amd64-3.7\pointnet2_ops
  copying pointnet2_ops\pointnet2_utils.py -> build\lib.win-amd64-3.7\pointnet2_ops
  copying pointnet2_ops\_version.py -> build\lib.win-amd64-3.7\pointnet2_ops
  copying pointnet2_ops\__init__.py -> build\lib.win-amd64-3.7\pointnet2_ops
  running egg_info
  creating pointnet2_ops.egg-info
  writing pointnet2_ops.egg-info\PKG-INFO
  writing dependency_links to pointnet2_ops.egg-info\dependency_links.txt
  writing requirements to pointnet2_ops.egg-info\requires.txt
  writing top-level names to pointnet2_ops.egg-info\top_level.txt
  writing manifest file 'pointnet2_ops.egg-info\SOURCES.txt'
  reading manifest file 'pointnet2_ops.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pointnet2_ops.egg-info\SOURCES.txt'
  creating build\lib.win-amd64-3.7\pointnet2_ops\_ext-src
  creating build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
  copying pointnet2_ops\_ext-src\include\ball_query.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
  copying pointnet2_ops\_ext-src\include\cuda_utils.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
  copying pointnet2_ops\_ext-src\include\group_points.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
  copying pointnet2_ops\_ext-src\include\interpolate.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
  copying pointnet2_ops\_ext-src\include\sampling.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
  copying pointnet2_ops\_ext-src\include\utils.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
  creating build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  copying pointnet2_ops\_ext-src\src\ball_query.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  copying pointnet2_ops\_ext-src\src\ball_query_gpu.cu -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  copying pointnet2_ops\_ext-src\src\bindings.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  copying pointnet2_ops\_ext-src\src\group_points.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  copying pointnet2_ops\_ext-src\src\group_points_gpu.cu -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  copying pointnet2_ops\_ext-src\src\interpolate.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  copying pointnet2_ops\_ext-src\src\interpolate_gpu.cu -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  copying pointnet2_ops\_ext-src\src\sampling.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  copying pointnet2_ops\_ext-src\src\sampling_gpu.cu -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
  running build_ext
  error: [WinError 2] 系统找不到指定的文件。
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "d:\python3.7\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
      return stream.closed
  ValueError: underlying buffer has been detached
  ----------------------------------------
  ERROR: Failed building wheel for pointnet2-ops
  Running setup.py clean for pointnet2-ops
Failed to build pointnet2-ops
Installing collected packages: pointnet2-ops
    Running setup.py install for pointnet2-ops ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\python3.7\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dongw\\AppData\\Local\\Temp\
\pip-req-build-ry1p4epw\\setup.py'"'"'; __file__='"'"'C:\\Users\\dongw\\AppData\\Local\\Temp\\pip-req-build-ry1p4epw\\setup.py'"'"';f = getattr(tok
enize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read(
).replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dongw\AppData\Local\Tem
p\pip-record-qk4a5am2\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python3.7\Include\pointnet2-ops'
         cwd: C:\Users\dongw\AppData\Local\Temp\pip-req-build-ry1p4epw\
    Complete output (46 lines):
    No CUDA runtime is found, using CUDA_HOME='D:\Anaconda3\pkgs\cudatoolkit-10.2.89-hb195166_8'
    running install
    d:\python3.7\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pi
p and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\pointnet2_ops
    copying pointnet2_ops\pointnet2_modules.py -> build\lib.win-amd64-3.7\pointnet2_ops
    copying pointnet2_ops\pointnet2_utils.py -> build\lib.win-amd64-3.7\pointnet2_ops
    copying pointnet2_ops\_version.py -> build\lib.win-amd64-3.7\pointnet2_ops
    copying pointnet2_ops\__init__.py -> build\lib.win-amd64-3.7\pointnet2_ops
    running egg_info
    writing pointnet2_ops.egg-info\PKG-INFO
    writing dependency_links to pointnet2_ops.egg-info\dependency_links.txt
    writing requirements to pointnet2_ops.egg-info\requires.txt
    writing top-level names to pointnet2_ops.egg-info\top_level.txt
    reading manifest file 'pointnet2_ops.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pointnet2_ops.egg-info\SOURCES.txt'
    creating build\lib.win-amd64-3.7\pointnet2_ops\_ext-src
    creating build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
    copying pointnet2_ops\_ext-src\include\ball_query.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
    copying pointnet2_ops\_ext-src\include\cuda_utils.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
    copying pointnet2_ops\_ext-src\include\group_points.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
    copying pointnet2_ops\_ext-src\include\interpolate.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
    copying pointnet2_ops\_ext-src\include\sampling.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
    copying pointnet2_ops\_ext-src\include\utils.h -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\include
    creating build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    copying pointnet2_ops\_ext-src\src\ball_query.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    copying pointnet2_ops\_ext-src\src\ball_query_gpu.cu -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    copying pointnet2_ops\_ext-src\src\bindings.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    copying pointnet2_ops\_ext-src\src\group_points.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    copying pointnet2_ops\_ext-src\src\group_points_gpu.cu -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    copying pointnet2_ops\_ext-src\src\interpolate.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    copying pointnet2_ops\_ext-src\src\interpolate_gpu.cu -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    copying pointnet2_ops\_ext-src\src\sampling.cpp -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    copying pointnet2_ops\_ext-src\src\sampling_gpu.cu -> build\lib.win-amd64-3.7\pointnet2_ops\_ext-src\src
    running build_ext
    error: [WinError 2] 系统找不到指定的文件。
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "d:\python3.7\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\python3.7\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Us
ers\\dongw\\AppData\\Local\\Temp\\pip-req-build-ry1p4epw\\setup.py'"'"'; __file__='"'"'C:\\Users\\dongw\\AppData\\Local\\Temp\\pip-req-build-ry1p4e
pw\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import se
tup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record
'C:\Users\dongw\AppData\Local\Temp\pip-record-qk4a5am2\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\pyth
on3.7\Include\pointnet2-ops' Check the logs for full command output.
WARNING: You are using pip version 21.2.2; however, version 22.0.4 is available.
You should consider upgrading via the 'd:\python3.7\python.exe -m pip install --upgrade pip' command.

when I run "pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib"",there another error:

dongw@DESKTOP-GA5B56C MINGW64 /d/Code/3DPointCloud/3DMedPT/3DMedPT-main
$ pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib"
Collecting pointnet2_ops
  Cloning git://github.com/erikwijmans/Pointnet2_PyTorch.git to c:\users\dongw\appdata\local\temp\pip-install-g3xifqxm\pointnet2-ops_83f6ce887be448
ff91a230f488e6962e
  Running command git clone -q git://github.com/erikwijmans/Pointnet2_PyTorch.git 'C:\Users\dongw\AppData\Local\Temp\pip-install-g3xifqxm\pointnet2
-ops_83f6ce887be448ff91a230f488e6962e'
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
WARNING: Discarding git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib. Command errored out wi
th exit status 128: git clone -q git://github.com/erikwijmans/Pointnet2_PyTorch.git 'C:\Users\dongw\AppData\Local\Temp\pip-install-g3xifqxm\pointne
t2-ops_83f6ce887be448ff91a230f488e6962e' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pointnet2-ops (unavailable) (from versions: none)
ERROR: No matching distribution found for pointnet2-ops (unavailable)

**Comment by crane-papercode** [comment]
Hi,
I am not quite sure what's happening there in windows, but you can always refer to https://github.com/erikwijmans/Pointnet2_PyTorch for your problem.
